// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeter.djinni

#pragma once

#include <string>

namespace grpcdemo {

class GreeterClient {
public:
    virtual ~GreeterClient() {}

    virtual std::string HeartBeat(const std::string & platform, const std::string & name, const std::string & pwd) = 0;

    virtual std::string LogOut(const std::string & platform, const std::string & name, const std::string & pwd) = 0;

    virtual std::string SignIn(const std::string & platform, const std::string & name, const std::string & pwd) = 0;

    virtual std::string SignUp(const std::string & name, const std::string & pwd) = 0;
};

}  // namespace grpcdemo
